### ISSUE TITLE
Copypaste error in description of sidecar and registry

### ISSUE THREAD

**Issue by ijsnellf** [amalgam8/amalgam8.github.io#59]
https://www.amalgam8.io/docs/

![capture](https://cloud.githubusercontent.com/assets/19473346/18591114/eeb1c77e-7bf6-11e6-83f7-fe6454290305.PNG)

These don't really describe the purpose of the components. Additionally, they seem to have a leftover colon from an earlier iteration of the documentation.

**Comment by rshriram** [comment]
Fixed with restructuring of docs.
