### ISSUE TITLE
API "Try It Out!" button question

### ISSUE THREAD

**Issue by travissalascox** [amalgam8/amalgam8.github.io#80]
I was playing around on the website for [Amalgam8](https://www.amalgam8.io) and saw that you had a tab to see the APIs. From the look of it, i guessed (and later confirmed by looking at this repo) that you were using swagger-ui to display it. Since you had a `Try It Out!` button, i figured i'd give it a try to see how things worked and what responses looked like, but noticed it doesn't seem you have an actual backend (although it does appear to be trying to call out to http://raw.githubusercontent.com for the base URL). Was just wondering, is something like that coming, even if it is just a mock server that spits out generic good path responses? If not, are you planning on displaying/removing the button so it doesn't lead to confusion for other?

**Comment by rshriram** [comment]
Thank you for pointing it out. Yes, its the standard swagger UI, but its hosted straight out of github and we don't have any hosted backends on which you can try these APIs out. It was something that @davetropeano put together quickly.

If you happen to know how to disable this in the swagger-ui.js, a PR would be greatly appreciated.
